apiVersion: apps/v1
kind: Deployment
metadata:
  name: 82227493-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 82227493-app
  template:
    metadata:
      labels:
        app: 82227493-app
    spec:
      containers:
      - name: 82227493-app
        image: cepgbaseacr.azurecr.io/82227493-app:latest
        ports:
        - containerPort: 8080
